-- Crear la tabla para guardar las suscripciones de notificaciones Push
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.public_users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    subscription_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configurar permisos RLS (Row Level Security)
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Permitir que los usuarios inserten, actualicen y eliminen sus propias suscripciones
CREATE POLICY "Users can insert their own subscriptions"
ON public.push_subscriptions FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "Users can view their own subscriptions"
ON public.push_subscriptions FOR SELECT
TO public
USING (true);

CREATE POLICY "Users can update their own subscriptions"
ON public.push_subscriptions FOR UPDATE
TO public
USING (true);

CREATE POLICY "Users can delete their own subscriptions"
ON public.push_subscriptions FOR DELETE
TO public
USING (true);
